function conf=strConf

conf=struct('nt', 5, ...
            'nr', 0, ...
            'fps', 25, ...
            'img_t', 80, ...
            'area_t', 0, ...
            'bin_t', 0, ...
            'roi_crop', zeros(1,4), ...
            'roi_cut', zeros(10,4), ...
            'blur_arg', [15 15 0 10], ...
            'fgislight', 0, ...
            'trktype', 0, ...
            'bb_blur', 0, ...
            'record_verify', 0, ...
            'length', 0, ...
            'breadth', 0, ...
            'split', 0, ...
            'crop_shape', 0, ...
            'shape_track', 0, ...
            'background', 0);

